export type AgentStatus = "active" | "beta" | "maintenance";
export type AgentChain = "BNB Chain" | "Ethereum" | "Arbitrum" | "Multi-chain";
export type QualityTier = "premium" | "quality" | "basic" | "unclassified";

export interface Agent {
  id: string;
  name: string;
  category: string;
  description: string;
  avatar: string;
  color: string;
  verified: boolean;
  status: AgentStatus;
  chain: AgentChain;
  rating: number;
  reviews: number;
  tasks: string;
  performance: number;
  uptime: number;
  price: string;
  priceNumeric: number;
  trend: string;
  lastActive: string;
  features: string[];
  builder: string;
  deployed: string;
  qualityTier?: QualityTier;
  score?: number;
  healthScore?: number | null;
  protocols?: string[];
  feedbackCount?: number;
  rank?: number | null;
  tokenId?: number;
  chainId?: number;
}

export const categories = [
  "All",
  "Security",
  "DeFi",
  "Analytics",
  "Portfolio",
  "Trading",
  "Compliance",
  "Cross-Chain",
];

export const agents: Agent[] = [
  {
    id: "sentinel-guard",
    name: "Sentinel Guard",
    category: "Security",
    description:
      "Real-time portfolio monitoring and threat detection across DeFi protocols. Auto-revoke compromised approvals.",
    avatar: "SG",
    color: "#22c55e",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.9,
    reviews: 342,
    tasks: "12.4k",
    performance: 98.7,
    uptime: 99.99,
    price: "0.5 BNB/mo",
    priceNumeric: 0.5,
    trend: "+18%",
    lastActive: "2 min ago",
    features: ["Auto-revoke", "Real-time alerts", "Multi-wallet"],
    builder: "SentinelLabs",
    deployed: "Mar 2025",
  },
  {
    id: "yield-oracle",
    name: "Yield Oracle",
    category: "DeFi",
    description:
      "Cross-protocol yield optimization with automated rebalancing. Finds highest APY across lending and LP pools.",
    avatar: "YO",
    color: "#3b82f6",
    verified: true,
    status: "active",
    chain: "BNB Chain",
    rating: 4.8,
    reviews: 287,
    tasks: "8.7k",
    performance: 96.2,
    uptime: 99.95,
    price: "1.2 BNB/mo",
    priceNumeric: 1.2,
    trend: "+24%",
    lastActive: "5 min ago",
    features: ["Auto-rebalance", "Multi-protocol", "Risk scoring"],
    builder: "DeFi Collective",
    deployed: "Jan 2025",
  },
  {
    id: "gas-optimizer",
    name: "Gas Optimizer",
    category: "Analytics",
    description:
      "Optimal gas timing, transaction simulation and batch execution. Saves 30-60% on average gas costs.",
    avatar: "GO",
    color: "#a855f7",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.7,
    reviews: 521,
    tasks: "21.3k",
    performance: 99.1,
    uptime: 99.98,
    price: "Free",
    priceNumeric: 0,
    trend: "+31%",
    lastActive: "1 min ago",
    features: ["Gas forecasting", "Batch tx", "Simulation"],
    builder: "ChainSight",
    deployed: "Nov 2024",
  },
  {
    id: "portfolio-pilot",
    name: "Portfolio Pilot",
    category: "Portfolio",
    description:
      "Automated portfolio management with risk-adjusted allocation. Rebalances based on market conditions.",
    avatar: "PP",
    color: "#f97316",
    verified: true,
    status: "active",
    chain: "BNB Chain",
    rating: 4.6,
    reviews: 198,
    tasks: "5.2k",
    performance: 94.8,
    uptime: 99.92,
    price: "0.8 BNB/mo",
    priceNumeric: 0.8,
    trend: "+12%",
    lastActive: "8 min ago",
    features: ["Auto-rebalance", "Risk model", "Tax reporting"],
    builder: "AlphaForge",
    deployed: "Feb 2025",
  },
  {
    id: "bridge-watch",
    name: "Bridge Watch",
    category: "Cross-Chain",
    description:
      "Cross-chain bridge monitoring, fee comparison and optimal routing. Detects bridge exploits in real-time.",
    avatar: "BW",
    color: "#06b6d4",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.5,
    reviews: 156,
    tasks: "3.8k",
    performance: 97.3,
    uptime: 99.88,
    price: "0.3 BNB/mo",
    priceNumeric: 0.3,
    trend: "+9%",
    lastActive: "12 min ago",
    features: ["Bridge alerts", "Fee tracking", "Route optimizer"],
    builder: "BridgeOps",
    deployed: "Apr 2025",
  },
  {
    id: "sentinel-pro",
    name: "Sentinel Pro",
    category: "Security",
    description:
      "Advanced threat intelligence with real-time alerting and auto-revoke. Enterprise-grade wallet protection.",
    avatar: "SP",
    color: "#22c55e",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.9,
    reviews: 412,
    tasks: "15.6k",
    performance: 99.4,
    uptime: 99.99,
    price: "2.0 BNB/mo",
    priceNumeric: 2.0,
    trend: "+42%",
    lastActive: "1 min ago",
    features: ["MEV protection", "Phishing shield", "Multi-sig support"],
    builder: "SentinelLabs",
    deployed: "Jun 2025",
  },
  {
    id: "mev-shield",
    name: "MEV Shield",
    category: "Trading",
    description:
      "Front-running and sandwich attack protection for onchain trades. Private mempool routing and slippage defense.",
    avatar: "MS",
    color: "#ef4444",
    verified: true,
    status: "active",
    chain: "BNB Chain",
    rating: 4.8,
    reviews: 334,
    tasks: "9.1k",
    performance: 97.8,
    uptime: 99.97,
    price: "0.6 BNB/mo",
    priceNumeric: 0.6,
    trend: "+15%",
    lastActive: "3 min ago",
    features: ["Private routing", "Slippage guard", "Flashbots"],
    builder: "ShieldOps",
    deployed: "May 2025",
  },
  {
    id: "compliance-sentinel",
    name: "Compliance Sentinel",
    category: "Compliance",
    description:
      "Transaction screening and regulatory compliance checks. Flags sanctioned addresses and high-risk interactions.",
    avatar: "CS",
    color: "#ec4899",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.4,
    reviews: 89,
    tasks: "2.1k",
    performance: 96.5,
    uptime: 99.94,
    price: "1.5 BNB/mo",
    priceNumeric: 1.5,
    trend: "+8%",
    lastActive: "15 min ago",
    features: ["OFAC screening", "Risk scoring", "Audit logs"],
    builder: "RegTech DAO",
    deployed: "Jul 2025",
  },
  {
    id: "dca-engine",
    name: "DCA Engine",
    category: "Trading",
    description:
      "Automated dollar-cost averaging across multiple tokens. Smart scheduling based on volatility and volume signals.",
    avatar: "DE",
    color: "#06b6d4",
    verified: true,
    status: "active",
    chain: "BNB Chain",
    rating: 4.5,
    reviews: 176,
    tasks: "4.3k",
    performance: 95.2,
    uptime: 99.91,
    price: "Free",
    priceNumeric: 0,
    trend: "+11%",
    lastActive: "6 min ago",
    features: ["Smart scheduling", "Multi-token", "Volatility tracking"],
    builder: "DCA Labs",
    deployed: "Dec 2024",
  },
  {
    id: "audit-trail",
    name: "Audit Trail",
    category: "Compliance",
    description:
      "Immutable onchain audit logging for all wallet interactions. Exportable reports for tax and compliance purposes.",
    avatar: "AT",
    color: "#8b5cf6",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.3,
    reviews: 67,
    tasks: "1.8k",
    performance: 98.2,
    uptime: 99.96,
    price: "0.4 BNB/mo",
    priceNumeric: 0.4,
    trend: "+6%",
    lastActive: "20 min ago",
    features: ["Immutable logs", "CSV export", "Tax reports"],
    builder: "RegTech DAO",
    deployed: "Aug 2025",
  },
  {
    id: "liquidity-radar",
    name: "Liquidity Radar",
    category: "DeFi",
    description:
      "Real-time liquidity monitoring across DEXs. Alerts for depth changes, whale movements and pool imbalances.",
    avatar: "LR",
    color: "#3b82f6",
    verified: true,
    status: "active",
    chain: "BNB Chain",
    rating: 4.6,
    reviews: 143,
    tasks: "3.2k",
    performance: 95.8,
    uptime: 99.89,
    price: "0.7 BNB/mo",
    priceNumeric: 0.7,
    trend: "+14%",
    lastActive: "4 min ago",
    features: ["Whale alerts", "Pool analytics", "Depth tracking"],
    builder: "DeFi Collective",
    deployed: "Mar 2025",
  },
  {
    id: "wallet-sentinel",
    name: "Wallet Sentinel",
    category: "Security",
    description:
      "Multi-wallet monitoring and threat detection. Scans approvals, contract interactions and suspicious activity.",
    avatar: "WS",
    color: "#22c55e",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.7,
    reviews: 256,
    tasks: "7.8k",
    performance: 98.1,
    uptime: 99.97,
    price: "0.3 BNB/mo",
    priceNumeric: 0.3,
    trend: "+20%",
    lastActive: "1 min ago",
    features: ["Approval scanner", "Multi-wallet", "Push alerts"],
    builder: "SentinelLabs",
    deployed: "Apr 2025",
  },
  {
    id: "sniper-alpha",
    name: "Sniper Alpha",
    category: "Trading",
    description:
      "Early token detection and sniper execution. Monitors new pool creation, liquidity adds and rug signals.",
    avatar: "SA",
    color: "#f59e0b",
    verified: true,
    status: "beta",
    chain: "BNB Chain",
    rating: 4.2,
    reviews: 94,
    tasks: "1.9k",
    performance: 91.3,
    uptime: 98.5,
    price: "1.8 BNB/mo",
    priceNumeric: 1.8,
    trend: "+35%",
    lastActive: "30 min ago",
    features: ["New pool scanner", "Rug detection", "Auto-snipe"],
    builder: "AlphaForge",
    deployed: "Jul 2025",
  },
  {
    id: "tax-reporter",
    name: "Tax Reporter",
    category: "Portfolio",
    description:
      "Automated tax reporting for onchain transactions. Generates jurisdiction-specific reports for DeFi activity.",
    avatar: "TR",
    color: "#10b981",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.4,
    reviews: 112,
    tasks: "2.6k",
    performance: 97.6,
    uptime: 99.93,
    price: "0.5 BNB/mo",
    priceNumeric: 0.5,
    trend: "+7%",
    lastActive: "1 hr ago",
    features: ["Auto-categorize", "PDF export", "Multi-jurisdiction"],
    builder: "RegTech DAO",
    deployed: "Jan 2025",
  },
  {
    id: "chain-scanner",
    name: "Chain Scanner",
    category: "Analytics",
    description:
      "Deep onchain analytics and wallet profiling. Track smart money, whale wallets and protocol TVL changes.",
    avatar: "CS",
    color: "#a855f7",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.6,
    reviews: 198,
    tasks: "6.1k",
    performance: 97.9,
    uptime: 99.95,
    price: "0.9 BNB/mo",
    priceNumeric: 0.9,
    trend: "+16%",
    lastActive: "2 min ago",
    features: ["Whale tracking", "TVL monitor", "Wallet profiler"],
    builder: "ChainSight",
    deployed: "Feb 2025",
  },
  {
    id: "apy-hunter",
    name: "APY Hunter",
    category: "DeFi",
    description:
      "Automated yield discovery across emerging protocols. Finds high-APY opportunities before they trend.",
    avatar: "AH",
    color: "#3b82f6",
    verified: true,
    status: "beta",
    chain: "BNB Chain",
    rating: 4.3,
    reviews: 78,
    tasks: "1.4k",
    performance: 93.4,
    uptime: 98.7,
    price: "1.0 BNB/mo",
    priceNumeric: 1.0,
    trend: "+28%",
    lastActive: "10 min ago",
    features: ["New protocol scanner", "Risk filter", "Auto-migrate"],
    builder: "DeFi Collective",
    deployed: "Jun 2025",
  },
  {
    id: "position-guard",
    name: "Position Guard",
    category: "Security",
    description:
      "DeFi position monitoring with liquidation protection. Alerts and auto-closes positions approaching risk thresholds.",
    avatar: "PG",
    color: "#22c55e",
    verified: true,
    status: "maintenance",
    chain: "BNB Chain",
    rating: 4.5,
    reviews: 134,
    tasks: "3.7k",
    performance: 96.8,
    uptime: 97.2,
    price: "0.4 BNB/mo",
    priceNumeric: 0.4,
    trend: "-2%",
    lastActive: "3 hr ago",
    features: ["Liquidation alerts", "Auto-close", "Health factor"],
    builder: "AlphaForge",
    deployed: "May 2025",
  },
  {
    id: "nft-watcher",
    name: "NFT Watcher",
    category: "Analytics",
    description:
      "NFT floor price monitoring, rarity tracking and wash trade detection across major marketplaces.",
    avatar: "NW",
    color: "#a855f7",
    verified: true,
    status: "active",
    chain: "Multi-chain",
    rating: 4.1,
    reviews: 56,
    tasks: "1.1k",
    performance: 94.1,
    uptime: 99.85,
    price: "Free",
    priceNumeric: 0,
    trend: "+5%",
    lastActive: "45 min ago",
    features: ["Floor alerts", "Rarity scoring", "Wash detection"],
    builder: "ChainSight",
    deployed: "Sep 2025",
  },
];
